
SRCS =		${wildcard ./mandatory/*.c}

OBJS 		= ${SRCS:.c=.o}

BONUS =		${wildcard ./bonus/*.c}
	  			
BONUS_OBJS	= ${BONUS:.c=.o}

CC			= cc
RM			= rm -f
CFLAGS		= -Wall -Wextra -Werror

NAME		= pipex

#_________________________________________________________
# Mandatory part
#$(NAME):	${OBJS}
#			${CC}  ${CFLAGS} -o ${NAME} ${OBJS}
#			@echo -e "$(GREEN)$(NAME) created!$(DEFAULT)"
#_________________________________________________________

#_________________________________________________________
# Mandatory + bonus
$(NAME):	${BONUS_OBJS}
			${CC}  ${CFLAGS} -o ${NAME} ${BONUS_OBJS}
			@echo -e "$(GREEN)$(NAME) created!$(DEFAULT)"
#_________________________________________________________

all:		${NAME}			

clean:
			${RM} ${OBJS} ${BONUS_OBJS}
			@echo -e "$(YELLOW)object files deleted!$(DEFAULT)"

fclean:		clean
			${RM} ${NAME}
			@echo -e "$(RED)all deleted!$(DEFAULT)"

re:			fclean all

.PHONY:		all clean fclean re

#COLORS
RED = \033[1;31m
GREEN = \033[1;32m
YELLOW = \033[1;33m
DEFAULT = \033[0m
